name: Load Data To Postgres

on:
  push:
    branches:
      - main
  # schedule:
    # - cron: "0 0 * * *"
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: false

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    env:
      SOURCES__STRIPE_ANALYTICS__STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
      DESTINATION__POSTGRES__CREDENTIALS__DATABASE: ${{ secrets.DATABASE }}
      DESTINATION__POSTGRES__CREDENTIALS__PASSWORD: ${{ secrets.PASSWORD }}
      DESTINATION__POSTGRES__CREDENTIALS__USERNAME: ${{ secrets.USERNAME }}
      DESTINATION__POSTGRES__CREDENTIALS__HOST: ${{ secrets.HOST }}
      DESTINATION__POSTGRES__CREDENTIALS__PORT: ${{ secrets.PORT }}
      DESTINATION__POSTGRES__CREDENTIALS__CONNECT_TIMEOUT: 15
      RUNTIME__LOG_LEVEL: CRITICAL

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip
      - name: Install dependencies
        run: pip install -r requirements.txt
      - name: Run
        run: python stripe_analytics_pipeline.py --dataset-name public full_load
